# -*- coding: utf-8 -*-
"""MMMv12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSJ_gfx5_eSv9HZf9Y85gZuOTpLfSl9e
"""

# @title This is the MMM models Spec that works

# 1) Install dependencies (colab + scenarioplanner + cuda — all in one pip call)
!pip -q install --upgrade google-meridian[colab,scenarioplanner,and-cuda]

# 2) Authenticate BigQuery + Drive + Sheets in one popup; mount Drive
from google.colab import auth, drive
import datetime

credentials = auth.authenticate_user([
    'https://www.googleapis.com/auth/bigquery',
    'https://www.googleapis.com/auth/drive',
    'https://www.googleapis.com/auth/spreadsheets',
])
drive.mount('/content/drive')

# 3) Imports
import arviz as az
import numpy as np
import pandas as pd
import pandas_gbq
from meridian import constants
from meridian.analysis import optimizer as budget_optimizer_module
from meridian.analysis import summarizer
from meridian.analysis import visualizer
from meridian.data import data_frame_input_data_builder as builder_module
from meridian.model import model as mmm_module
from meridian.model import prior_distribution
from meridian.model import spec
import tensorflow as tf
import tensorflow_probability as tfp

# 4) Runtime checks
print("GPU Available:", len(tf.config.list_physical_devices('GPU')) > 0)
print("TensorFlow version:", tf.__version__)

# 5) Pull data from BigQuery
project_id = 'donut-426'
view_sql = """SELECT * FROM abc.mmm WHERE Model_Dates = 'In Model'"""

df_bq = pandas_gbq.read_gbq(view_sql, project_id=project_id)
if 'time' not in df_bq.columns:
    raise ValueError("Expected a 'time' column in BigQuery data.")
df_bq['time'] = pd.to_datetime(df_bq['time'])

# 6) Define channels and variables
media_channels = ['Meta', 'Search', 'PMAX', 'Amex',
                  'Video_Epsilon', 'Video_Google', 'Video_Hulu', 'Video_MNTN', 'Video_Paramount']
media_impression_cols = ['Meta_impression', 'Search_click', 'PMAX_impression', 'Amex_impression',
                         'Video_Epsilon_impression', 'Video_Google_impression', 'Video_Hulu_impression',
                         'Video_MNTN_impression', 'Video_Paramount_impression']
media_spend_cols = [f"{ch}_spend" for ch in media_channels]

non_media_cols = ['Vault_Drops', 'Email_sends', 'Conversions_BasketSize', 'Conversions_Pricing',
                  'StoreCount', 'Celebs', 'Redemptions_Other','Redemptions_Birthday_Signup']

control_cols = ['Category_Interest', 'Hurricanes', 'LightningSales']

population_col = 'population' if 'population' in df_bq.columns else None

required_cols = ['time', 'geo', 'Conversions_Revenue'] + media_impression_cols + media_spend_cols + non_media_cols + control_cols
missing = [c for c in required_cols if c not in df_bq.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}. Verify your BigQuery schema.")
print("All key columns present. Shape:", df_bq.shape)

# 7) Build Meridian InputData
builder = builder_module.DataFrameInputDataBuilder(
    kpi_type='revenue',
    default_kpi_column='Conversions_Revenue'
)
builder = builder.with_kpi(df_bq)
builder = builder.with_media(
    df_bq,
    media_cols=media_impression_cols,
    media_spend_cols=media_spend_cols,
    media_channels=media_channels
)
if population_col:
    builder = builder.with_population(df_bq, population_col=population_col)
builder = builder.with_non_media_treatments(df_bq, non_media_treatment_cols=non_media_cols)
builder = builder.with_controls(df_bq, control_cols=control_cols)
input_data = builder.build()
print("Input Data built successfully.")

# 8) Priors — ROI, adstock alpha, hill ec (vectorized)
roi_mu = tf.constant([
    1.40,  # Meta
    1.35,  # Search
    1.15,  # PMAX
    1.15,  # Amex
    1.65, 1.65, 1.65, 1.65, 1.65   # Video group: center ~5.2× (exp(1.65)≈5.2)
], dtype=tf.float32)

roi_sigma = tf.constant([
    0.40,  # Meta
    0.28,  # Search: tight → 95% mass ~2.2–6.5×
    0.45,  # PMAX
    0.45,  # Amex
    0.25, 0.25, 0.25, 0.25, 0.25   # Video group
], dtype=tf.float32)

roi_prior = tfp.distributions.LogNormal(loc=roi_mu, scale=roi_sigma)

alpha_conc1 = tf.constant([2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0], dtype=tf.float32)
alpha_conc0 = tf.constant([2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0], dtype=tf.float32)
alpha_prior = tfp.distributions.Beta(concentration1=alpha_conc1, concentration0=alpha_conc0)

ec_mu = tf.constant([1.0] * 9, dtype=tf.float32)
ec_sigma = tf.constant([
    0.5, 0.5, 0.5, 0.5,
    0.30, 0.30, 0.30, 0.30, 0.30
], dtype=tf.float32)
ec_prior = tfp.distributions.TruncatedNormal(loc=ec_mu, scale=ec_sigma, low=0.1, high=10.0)

prior = prior_distribution.PriorDistribution(
    roi_m=roi_prior,
    alpha_m=alpha_prior,
    ec_m=ec_prior,
)
print("Custom vectorized priors defined (slope fixed to 1.0).")

adstock_map = {
    "Search":          "geometric",
    "Meta":            "geometric",
    "PMAX":            "geometric",
    "Amex":            "geometric",
    "Video_Epsilon":   "binomial",
    "Video_Google":    "binomial",
    "Video_Hulu":      "binomial",
    "Video_MNTN":      "binomial",
    "Video_Paramount": "binomial",
}

# 9) Model spec
model_spec = spec.ModelSpec(
    prior=prior,
    media_effects_dist='log_normal',
    adstock_decay_spec=adstock_map,
    max_lag=12,
    hill_before_adstock=True
)
print("Model spec created.")

# 10) Fit model
mmm = mmm_module.Meridian(input_data=input_data, model_spec=model_spec)
print("Meridian model initialized.")

mmm.sample_prior(500)
mmm.sample_posterior(
    n_chains=20,
    n_adapt=3000,
    n_burnin=1000,
    n_keep=3000,
    seed=0,
    dual_averaging_kwargs={'target_accept_prob': 0.85},
)
print("Posterior sampling completed.")

# @title This is the Model Diagnostics and single html report builder
# 11) Diagnostics
model_diagnostics = visualizer.ModelDiagnostics(mmm)
model_diagnostics.plot_rhat_boxplot()
model_diagnostics.plot_prior_and_posterior_distribution(parameter='roi_m')
model_diagnostics.plot_prior_and_posterior_distribution(parameter='beta_m')
model_diagnostics.plot_prior_and_posterior_distribution(parameter='beta_gm')
model_diagnostics.plot_prior_and_posterior_distribution(parameter='ec_m')
visualizer.ModelFit(mmm).plot_model_fit(include_ci=True)

inference_data = mmm.inference_data
parameters_to_plot = ['roi_m', 'beta_m', 'beta_gm', 'ec_m']
az.Numba.disable_numba()
for param in parameters_to_plot:
    az.plot_trace(
        inference_data,
        var_names=param,
        compact=False,
        backend_kwargs={"constrained_layout": True},
    )
az.plot_ess(inference_data, kind='local', var_names=parameters_to_plot)
print(az.summary(inference_data, var_names=parameters_to_plot))

# 12) Summary HTML export
mmm_summarizer = summarizer.Summarizer(mmm)
start_date, end_date = '2025-04-27', '2026-04-26' #these should 52 or 53 of the week start days
out_dir = '/content/drive/MyDrive/ABC/MMM'
now = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
filename = f"v12_summary_output_{start_date}_to_{end_date}_{now}.html"

mmm_summarizer.output_model_results_summary(
    filename=filename,
    filepath=out_dir,
    start_date=start_date,
    end_date=end_date,
)
print(f"Model results saved to {out_dir}/{filename}")

model_diagnostics.plot_rhat_boxplot()

# @title Scenario planner builder (takes 45min)

from IPython.display import HTML

from meridian.schema.processors import (
    model_fit_processor,
    marketing_processor,
    budget_optimization_processor,
)
from meridian.schema.utils import date_range_bucketing
from scenarioplanner.converters import sheets
from scenarioplanner.converters.dataframe import dataframe_model_converter
from scenarioplanner import mmm_ui_proto_generator as mmm_ui_gen
from scenarioplanner.linkingapi import url_generator

print('Scenario Planner imports ready.')

spreadsheet_name = 'ABC MMM Scenario Planner (yearly) — FY26'  # @param {"type":"string"}
optimization_name = 'ABC FY26'  # @param {"type":"string"}
include_non_paid_channels = True  # @param {"type":"boolean"}

yearly = True       # @param {"type":"boolean"}
quarterly = True     # @param {"type":"boolean"}
monthly = False      # @param {"type":"boolean"}

min_spend_shift_ratio = 0.40  # @param {"type":"raw"}
max_spend_shift_ratio = 0.40  # @param {"type":"raw"}
use_optimal_frequency = False  # @param {"type":"boolean"}

max_frequency = 10.0          # @param {"type":"raw"}

time_breakdown_generators = []
if yearly:    time_breakdown_generators.append(date_range_bucketing.YearlyDateRangeGenerator)
if quarterly: time_breakdown_generators.append(date_range_bucketing.QuarterlyDateRangeGenerator)
if monthly:   time_breakdown_generators.append(date_range_bucketing.MonthlyDateRangeGenerator)

channel_constraints = [
    budget_optimization_processor.ChannelConstraintRel(
        channel_name=ch,
        spend_constraint_lower=min_spend_shift_ratio,
        spend_constraint_upper=max_spend_shift_ratio,
    )
    for ch in mmm.input_data.get_all_paid_channels()
]

budget_opt_spec = budget_optimization_processor.BudgetOptimizationSpec(
    start_date=None,
    end_date=None,
    optimization_name=optimization_name,
    grid_name='-'.join(optimization_name.lower().split(' ')),
    constraints=channel_constraints,
    use_optimal_frequency=use_optimal_frequency,
    max_frequency=max_frequency,
)

print('Running scenario inference — ~45 min on h1100.')
mmm_proto = mmm_ui_gen.create_mmm_ui_data_proto(
    mmm=mmm,
    specs=[
        model_fit_processor.ModelFitSpec(),
        marketing_processor.MarketingAnalysisSpec(
            media_summary_spec=marketing_processor.MediaSummarySpec(
                include_non_paid_channels=include_non_paid_channels,
            ),
        ),
        budget_opt_spec,
    ],
    time_breakdown_generators=time_breakdown_generators,
)

print('Converting to dataframes.')
dataframes = dataframe_model_converter.DataFrameModelConverter(mmm_proto)()

print('Uploading to Google Sheets.')
spreadsheet = sheets.upload_to_gsheet(
    dataframes, credentials, spreadsheet_name=spreadsheet_name,
)
print(f'Spreadsheet URL: {spreadsheet.url}')

# @ title Scenario Planner exporter to gSheet
report_url = url_generator.create_report_url(spreadsheet)
HTML(f'<a href="{report_url}" target="_blank">Open ABC MMM Scenario Planner in Looker Studio</a>')