# -*- coding: utf-8 -*-
"""MMMv10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-BCaMp9hhf4mqIYd4zZ6v5FH-P_H9M0

This version now has celebs added as a test control
"""

# -*- coding: utf-8 -*-
# ABC Media Mix Model in Colab using Google Meridian (vectorized priors + auto notebook name)
# ------------------------------------------------------------------------------------------

# 1) Install dependencies
!pip -q install --upgrade google-meridian[colab,and-cuda]

# 2) Authenticate BigQuery + mount Drive
from google.colab import auth, drive
import datetime

auth.authenticate_user()
drive.mount('/content/drive')

# 3) Imports
import arviz as az
import numpy as np
import pandas as pd
import pandas_gbq
from meridian import constants
from meridian.analysis import optimizer as budget_optimizer_module
from meridian.analysis import summarizer
from meridian.analysis import visualizer
from meridian.data import data_frame_input_data_builder as builder_module
from meridian.model import model as mmm_module
from meridian.model import prior_distribution
from meridian.model import spec
import tensorflow as tf
import tensorflow_probability as tfp

# 4) Runtime checks
print("GPU Available:", len(tf.config.list_physical_devices('GPU')) > 0)
print("TensorFlow version:", tf.__version__)

# 5) Pull data from BigQuery
project_id = 'donut-426'
view_sql = """SELECT * FROM abc.mmm WHERE Model_Dates = 'In Model'"""

df_bq = pandas_gbq.read_gbq(view_sql, project_id=project_id)
if 'time' not in df_bq.columns:
    raise ValueError("Expected a 'time' column in BigQuery data.")
df_bq['time'] = pd.to_datetime(df_bq['time'])

# 6) Define channels and variables
media_channels = ['Meta', 'Search', 'PMAX', 'Amex',
                  'Video_Epsilon', 'Video_Google', 'Video_Hulu', 'Video_MNTN', 'Video_Paramount'
]
media_impression_cols = ['Meta_impression', 'Search_click', 'PMAX_impression', 'Amex_impression',
                         'Video_Epsilon_impression', 'Video_Google_impression', 'Video_Hulu_impression', 'Video_MNTN_impression', 'Video_Paramount_impression'
]
media_spend_cols = [f"{ch}_spend" for ch in media_channels]
non_media_cols = ['Vault_Drops', 'Email_sends', 'Conversions_BasketSize','Conversions_Pricing','StoreCount','Celebs' ]
control_cols = ['Category_Interest','Hurricanes','LightningSales']

population_col = 'population' if 'population' in df_bq.columns else None

required_cols = ['time', 'geo', 'Conversions_Revenue'] + media_impression_cols + media_spend_cols + non_media_cols + control_cols
missing = [c for c in required_cols if c not in df_bq.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}. Verify your BigQuery schema.")
print("All key columns present. Shape:", df_bq.shape)

# 7) Build Meridian InputData
builder = builder_module.DataFrameInputDataBuilder(
    kpi_type='revenue',
    default_kpi_column='Conversions_Revenue'
)

builder = builder.with_kpi(df_bq)
builder = builder.with_media(
    df_bq,
    media_cols=media_impression_cols,
    media_spend_cols=media_spend_cols,
    media_channels=media_channels
)
if population_col:
    builder = builder.with_population(df_bq, population_col=population_col)

builder = builder.with_non_media_treatments(df_bq, non_media_treatment_cols=non_media_cols)
builder = builder.with_controls(df_bq, control_cols=control_cols)
input_data = builder.build()
print("Input Data built successfully.")


# Updated ROI priors — Search gets the tightest & most centered prior
roi_mu = tf.constant([
    1.40,          # Meta
    1.35,          # Search
    1.15,          # PMAX
    1.15,          # Amex
    1.65, 1.65, 1.65, 1.65, 1.65   # Video group: center ~5.2× (exp(1.65)≈5.2)
], dtype=tf.float32)

roi_sigma = tf.constant([
    0.40,          # Meta: still somewhat wide
    0.28,          # Search: tight → ~95% of mass roughly between ~2.2–6.5× (covers 3–5 nicely)
    0.45,          # PMAX: wider uncertainty
#   0.38,          # Video
    0.45,           # Amex: wider uncertainty testing
    0.25, 0.25, 0.25, 0.25, 0.25 #all the video partners get the the same


], dtype=tf.float32)

roi_prior = tfp.distributions.LogNormal(loc=roi_mu, scale=roi_sigma)


# Adstock alpha prior — identical Beta for each channel via vectorized concentrations
alpha_conc1 = tf.constant([2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0], dtype=tf.float32)
alpha_conc0 = tf.constant([2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0], dtype=tf.float32)
alpha_prior = tfp.distributions.Beta(concentration1=alpha_conc1, concentration0=alpha_conc0)

# Hill ec prior — vectorized TruncatedNormal
ec_mu = tf.constant([1.0]*9, dtype=tf.float32)  # keep neutral

ec_sigma = tf.constant([
    0.5, 0.5, 0.5, 0.5,               # non-video keep wide
    0.30, 0.30, 0.30, 0.30, 0.30      # video tighter → 95% ~0.4–1.6 range
], dtype=tf.float32)

ec_prior = tfp.distributions.TruncatedNormal(loc=ec_mu, scale=ec_sigma, low=0.1, high=10.0)

# Optional: Slope prior (uncomment to allow flexible Hill slopes; fixed=1.0 by default)
# slope_mu    = tf.constant([0.0, 0.0, 0.0, 0.0], dtype=tf.float32)  # Centered on log(1)=0
# slope_sigma = tf.constant([0.5, 0.5, 0.5, 0.5], dtype=tf.float32)
# slope_prior = tfp.distributions.LogNormal(loc=slope_mu, scale=slope_sigma)

prior = prior_distribution.PriorDistribution(
    roi_m=roi_prior,
    alpha_m=alpha_prior,
    ec_m=ec_prior,
    # slope_m=slope_prior  # Uncomment if enabling
)
print("Custom vectorized priors defined (slope fixed to 1.0).")

# Mix ad-stock distro by channel
# Use binomial for video-like channels; geometric for the rest
adstock_map = {
    "Search"      : "geometric",
    "Meta"        : "geometric",
    "PMAX"        : "geometric",
 # "Video"        : "binomial",
    "Amex"        : "geometric",
   "Video_Epsilon": "binomial",
    "Video_Google": "binomial",
     "Video_Hulu" : "binomial",
     "Video_MNTN" : "binomial",
 "Video_Paramount": "binomial"
  #"Video_Peacock" : "binomial"


}

# 9) Model spec
model_spec = spec.ModelSpec(
    prior=prior,
    media_effects_dist='log_normal',
    adstock_decay_spec=adstock_map,
    max_lag=12,
    hill_before_adstock=True
)
print("Model spec created.")

# 10) Fit model
mmm = mmm_module.Meridian(input_data=input_data, model_spec=model_spec)
print("Meridian model initialized.")

# Prior predictive and posterior
mmm.sample_prior(500)
mmm.sample_posterior(
    n_chains=20,  # Increased for GPU parallelism
    n_adapt=3000,  # Slightly reduced for speed (monitor R-hat)
    n_burnin=1000,
    n_keep=3000,
    seed=0,
    dual_averaging_kwargs={'target_accept_prob': 0.85}  # Tune for faster adaptation
)
print("Posterior sampling completed.")

# 11) Diagnostics + Fit
model_diagnostics = visualizer.ModelDiagnostics(mmm)

# R-hat boxplot (existing)
model_diagnostics.plot_rhat_boxplot()

# Prior and posterior distributions for key parameters
model_diagnostics.plot_prior_and_posterior_distribution(parameter='roi_m')
model_diagnostics.plot_prior_and_posterior_distribution(parameter='beta_m')
model_diagnostics.plot_prior_and_posterior_distribution(parameter='beta_gm')
model_diagnostics.plot_prior_and_posterior_distribution(parameter='ec_m')

# Model fit plot with uncertainty intervals
visualizer.ModelFit(mmm).plot_model_fit(include_ci=True)

# Trace and density plots via ArviZ (includes trace for chain mixing)
inference_data = mmm.inference_data  # Corrected attribute (no underscore)
parameters_to_plot = ['roi_m', 'beta_m', 'beta_gm', 'ec_m']
for param in parameters_to_plot:
    az.plot_trace(
        inference_data,
        var_names=param,
        compact=False,
        backend_kwargs={"constrained_layout": True},
    )

# Effective sample size (ESS) plots via ArviZ – aim for >200 per param
az.plot_ess(inference_data, kind='local', var_names=parameters_to_plot)

# Raw summary stats via ArviZ (includes rhat, ess_mean, ess_bulk, etc.)
print(az.summary(inference_data, var_names=parameters_to_plot))

# 12) Summaries / HTML export with auto-detected notebook name
mmm_summarizer = summarizer.Summarizer(mmm)
start_date, end_date = '2025-02-23', '2026-02-15' #need to use week start dates
out_dir = '/content/drive/MyDrive/ABC/MMM'

now = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
filename = f"v10_summary_output_{start_date}_to_{end_date}_{now}.html"

mmm_summarizer.output_model_results_summary(
    filename=filename,
    filepath=out_dir,
    start_date=start_date,
    end_date=end_date
)
print(f"Model results saved to {out_dir}/{filename}")

# Plot R-hat boxplot
model_diagnostics.plot_rhat_boxplot()

"""The Cell below is me starting to test Scenario Planner"""

# @title
# 0) Install Meridian if missing
try:
    import meridian
except ImportError:
    print("Meridian library not found. Installing... (this may take a minute)")
    !pip -q install --upgrade google-meridian[colab,and-cuda]
    print("Installation complete.")

# Ensure dependencies are imported
from meridian.analysis import optimizer as budget_optimizer_module

# Check if the model 'mmm' exists
if 'mmm' not in locals() and 'mmm' not in globals():
    print("⚠️ Model 'mmm' not found!")
    print("Please run the model training cell (Cell -kfYHgmVX_KO) above to fit the model first.")
    print("Once the model is trained, re-run this cell to generate the optimization scenario.")
else:
    print("\n--- Setting up Budget Optimizer ---")

    # 1) Initialize the BudgetOptimizer with the fitted MMM model
    budget_optimizer = budget_optimizer_module.BudgetOptimizer(mmm)

    # 2) Define your optimization parameters
    # Note: The optimizer requires dates that exist within the model's input data.
    # We will use the last ~4 weeks of data as an example.
    optimization_start_date = '2025-12-29'
    optimization_end_date = '2026-01-25'
    hypothetical_total_budget = 500000.0

    # 3) Run the optimization
    print(f"Optimizing budget of ${hypothetical_total_budget:,.2f} for {optimization_start_date} to {optimization_end_date}...")

    try:
        # The optimize method calculates the optimal spend allocation
        optimization_results = budget_optimizer.optimize(
            start_date=optimization_start_date,
            end_date=optimization_end_date,
            budget=hypothetical_total_budget
        )

        print("\n--- Optimization Results ---")
        print(optimization_results)

        # Helper to print attributes if it's an object
        if hasattr(optimization_results, '__dict__'):
            print("\nResult Attributes:", optimization_results.__dict__.keys())

        # Attempt to access likely attributes for spend allocation
        if hasattr(optimization_results, 'optimal_spend'):
             print("\nOptimal Spend:\n", optimization_results.optimal_spend)

    except Exception as e:
        print(f"Optimization encountered an error: {e}")
        print("Available methods in budget_optimizer:", dir(budget_optimizer))

"""This Cell below builds the Monthly Spend, Revenue and ROAs Columns Extract"""

# @title
# After mmm is fitted and you have inference_data or analyzer ready
import pandas as pd
import numpy as np
from meridian.analysis import analyzer as analyzer_module

analyzer = analyzer_module.Analyzer(mmm)

# Get monthly incremental revenue by channel
# First, ensure your time is monthly-resampled if weekly
df_monthly = df_bq.copy()
df_monthly['month'] = df_monthly['time'].dt.to_period('M').dt.to_timestamp()

# Aggregate actual spend by month/channel
monthly_spend = df_monthly.groupby('month')[media_spend_cols].sum().reset_index()
monthly_spend = monthly_spend.melt(id_vars='month', value_vars=media_spend_cols,
                                   var_name='channel_spend', value_name='spend')
monthly_spend['channel'] = monthly_spend['channel_spend'].str.replace('_spend', '')

# Get modeled incremental revenue by channel over time using Analyzer
# incremental_outcome returns tensor: (chains, draws, [geos], times, channels)
# We request: aggregate_geos=True, aggregate_times=False, include_non_paid_channels=False (only paid)
print("Calculating incremental outcomes...")
inc_tensor = analyzer.incremental_outcome(
    aggregate_geos=True,
    aggregate_times=False,
    include_non_paid_channels=False
)

# Convert tensor to numpy and calculate mean over chains (0) and draws (1)
# Shape becomes (n_times, n_channels)
inc_mean = np.mean(inc_tensor.numpy(), axis=(0, 1))

# Create DataFrame
# The order of columns matches input_data.media_channels (which is 'media_channels' var)
inc_by_time = pd.DataFrame(inc_mean, columns=media_channels)

# Add time column
# We assume the time dimension matches the input data time periods
inc_by_time['time'] = df_bq['time'].values

# Create 'month' column to match monthly_spend alignment (Start of Month)
inc_by_time['time'] = pd.to_datetime(inc_by_time['time'])
inc_by_time['month'] = inc_by_time['time'].dt.to_period('M').dt.to_timestamp()

# Melt to long format
inc_by_time = inc_by_time.melt(id_vars=['time', 'month'], var_name='channel', value_name='mean')

# Calculate ROAS = incremental_rev / spend per month/channel
# Group by 'month' (not 'time') to ensure keys match monthly_spend
monthly_roas = inc_by_time.groupby(['month', 'channel'])['mean'].sum().reset_index()

# Merge with spend data
monthly_roas = monthly_roas.merge(monthly_spend[['month', 'channel', 'spend']], on=['month', 'channel'])

monthly_roas['roas'] = monthly_roas['mean'] / monthly_roas['spend']  # incremental revenue / spend = ROAS

# Clean up
monthly_table = monthly_roas.pivot(index='month', columns='channel', values=['spend', 'roas', 'mean'])
monthly_table.columns = ['_'.join(col).strip() for col in monthly_table.columns.values]
monthly_table.reset_index(inplace=True)

# Export to CSV (easy) or HTML
monthly_table.to_csv(f'{out_dir}/monthly_spend_roas_by_channel.csv', index=False)

# Bonus: Pretty HTML table
html_table = monthly_table.to_html(index=False, float_format='%.2f')
with open(f'{out_dir}/monthly_spend_roas_table.html', 'w') as f:
    f.write(html_table)
print("Monthly spend & ROAS table saved!")

# Display first few rows
print(monthly_table.head())